# -----------------------
# Kong configuration file
# -----------------------
#
# You can find every available setting in the provided file:
# /etc/kong/kong.conf.default

#------------------------------------------------------------------------------
# DATASTORE
#------------------------------------------------------------------------------

database = postgres
pg_host = 127.0.0.1
pg_port = 5432
pg_user = kong_user
pg_password = kong_password
